baseURL = 'https://bearxz.github.io/'
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 是否包括中日韩文字
dateFormat = '2006-01-02'
enablePWA = true
hasCJKLanguage = true
images = ['/assets/logo.ong']
title = '十二楼五城'

# 作者配置
[author]
avatar = "/assets/author.png" # FixIt 0.2.18 | 新增
email = "" 
link = "" 
name = "bearxz" 

# 主题
theme = 'FixIt'
[menu]
[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "分类"
title = ""
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/hugo-fixit/FixIt/issues/43)
noClasses = false

# 页面头部导航栏配置
[params.header]
# FixIt 0.2.13 | 更改 桌面端导航栏模式 ["sticky", "normal", "auto"]
desktopMode = "sticky"
# FixIt 0.2.13 | 更改 移动端导航栏模式 ["sticky", "normal", "auto"]
mobileMode = "auto"
# FixIt 0.2.0 | 新增 页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = "/logo.svg"
# 标题名称
name = "十二楼五城"
# 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
pre = ""
# 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
post = ""
# FixIt 0.2.5 | 新增 是否为标题显示打字机动画
typeit = false
# FixIt 0.2.12 | 新增 页面头部导航栏副标题配置
[params.header.subtitle]
# 副标题名称
name = "天上白玉京，十二楼五城"
# 是否为副标题显示打字机动画
typeit = true

# FixIt 0.2.16 | 新增 阅读进度条
[params.readingProgress]
enable = true
# 可用值：["left", "right"]
start = "left"
# 可用值：["top", "bottom"]
dark = ""
height = "2px"
light = ""
position = "top"
reversed = false

# FixIt 0.2.17 | 新增 页面加载期间顶部的进度条
# 有关详细信息：https://github.com/CodeByZach/pace
[params.pace]
enable = false
# 所有可用颜色：
# ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
color = "orange"
# 所有可用主题：
# ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
# "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
theme = "minimal"

# FixIt 0.2.14 | 新增 在左上角或者右上角显示 GitHub 开源链接
[params.githubCorner]
enable = true 
permalink = "https://github.com/bearxz/bearxz.github.io" 
position = "right" # ["left", "right"]
title = "在 GitHub 上查看源代码"
